/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_login (void);
GtkWidget* create_inscription2 (void);
GtkWidget* create_menu_admin3 (void);
GtkWidget* create_menu_citoy4 (void);
GtkWidget* create_wissal1 (void);
GtkWidget* create_wissal2 (void);
GtkWidget* create_wissal3 (void);
GtkWidget* create_wissal4 (void);
GtkWidget* create_modifierhadil (void);
GtkWidget* create_ajouterhadil (void);
GtkWidget* create_hadil6 (void);
GtkWidget* create_touscitoyen (void);
GtkWidget* create_hadil10 (void);
GtkWidget* create_farah1 (void);
GtkWidget* create_farah2 (void);
GtkWidget* create_farah3 (void);
GtkWidget* create_farah4 (void);
GtkWidget* create_profil (void);
